name: Rust release
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf, i686-unknown-linux-gnu, arm-unknown-linux-gnueabi, x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Install gcc-libs
        run: |
          sudo apt install gcc-multilib

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          # use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../chapchap-${{ matrix.target }}.tar.gz chapchap
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          files: 'chapchap*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
